{
 "title": "MicroPython Workshop",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rolls over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "roll", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Rolls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(roll[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Rolls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (last_over_time(roll[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rolls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time(roll[1d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}