{
 "title": "MicroPython Workshop",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latest Rolls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (last_over_time(roll[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Rolls",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (count_over_time(roll[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Score Rolled",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum_over_time(roll[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Recent Values",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "roll", "legendFormat": "__auto" }
   ]
  }
 ]
}