services:
  ntp:
    container_name: ntp
    image: cturra/ntp
    ports:
      - 123:123
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports: 
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure